In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets

In [18]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_boston',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_class

In [19]:
iris=datasets.load_iris()

In [20]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [21]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [22]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [23]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [24]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [25]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [26]:
x=iris.data
y=iris.target

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.33, random_state=43)

# Linear Regression

In [29]:
from sklearn.preprocessing import StandardScaler
sc1 = StandardScaler()
xtrain = sc1.fit_transform(xtrain)
xtest = sc1.fit_transform(xtest)

In [30]:
from sklearn.linear_model import LinearRegression

In [31]:
reg= LinearRegression()
reg.fit(xtrain,ytrain)

LinearRegression()

In [32]:
y_test_pred = reg.predict(xtest)

In [33]:
y_test_pred

array([-0.03632475, -0.11445869,  1.70183232,  1.0205359 ,  2.20367236,
       -0.08893516,  1.91663644,  1.17395672,  0.9557883 ,  0.90786796,
       -0.07404358,  1.37541158,  2.15627768, -0.04248052,  1.43154207,
        1.23465859, -0.02080223, -0.14852515,  2.19552775,  2.42551662,
       -0.16849772, -0.0139069 , -0.08887704,  1.62091533,  1.69061415,
        2.40925211, -0.04714956,  1.23162953, -0.10113047, -0.11807397,
        1.24949204, -0.02983374,  0.90225887,  0.88738833,  1.8931809 ,
        1.86867403,  1.32841026,  2.17656942,  0.99200191,  1.46013419,
        1.0603277 ,  1.86103405,  1.04656903,  1.62783932, -0.17209197,
        1.32195877,  1.25060392,  0.88941923,  1.28303041,  1.51460366])

In [34]:
ytest

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       0, 1, 1, 1, 1, 1])

In [35]:
reg.coef_

array([-0.06182203, -0.00879948,  0.39988998,  0.47535494])

In [36]:
reg.intercept_

1.02

In [37]:
reg.score(xtrain,ytrain)

0.9324091611797232

In [53]:
from sklearn.metrics import r2_score

In [54]:
r2_score(ytest,ypred)

0.9283667621776505

# KNN

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier

In [41]:
knn=KNeighborsClassifier()

In [42]:
knn.fit(xtrain,ytrain)

KNeighborsClassifier()

In [43]:
knn.score(xtrain,ytrain)

0.95

In [45]:
ypred=knn.predict(xtest)
ypred

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2,
       0, 1, 1, 1, 1, 2])

In [46]:
ytest

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       0, 1, 1, 1, 1, 1])

In [47]:
accuracy_score(ytest,ypred)

0.96

In [48]:
confusion_matrix(ytest,ypred)

array([[15,  0,  0],
       [ 0, 20,  2],
       [ 0,  0, 13]], dtype=int64)

In [52]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.91      0.95        22
           2       0.87      1.00      0.93        13

    accuracy                           0.96        50
   macro avg       0.96      0.97      0.96        50
weighted avg       0.97      0.96      0.96        50



# Naive bayes

In [56]:
from sklearn.naive_bayes import GaussianNB

In [57]:
nb=GaussianNB()

In [59]:
nb.fit(xtrain,ytrain)

GaussianNB()

In [60]:
nb.score(xtrain,ytrain)

0.96

In [62]:
ypred=nb.predict(xtest)
ypred

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 2,
       0, 1, 1, 1, 1, 2])

In [63]:
ytest

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       0, 1, 1, 1, 1, 1])

In [64]:
accuracy_score(ytest,ypred)

0.92

In [65]:
confusion_matrix(ytest,ypred)

array([[15,  0,  0],
       [ 0, 18,  4],
       [ 0,  0, 13]], dtype=int64)

In [67]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.82      0.90        22
           2       0.76      1.00      0.87        13

    accuracy                           0.92        50
   macro avg       0.92      0.94      0.92        50
weighted avg       0.94      0.92      0.92        50



# Logestic Regression

In [68]:
from sklearn.linear_model import LogisticRegression

In [69]:
lr=LogisticRegression()

In [70]:
lr.fit(xtrain,ytrain)

LogisticRegression()

In [71]:
lr.score(xtrain,ytrain)

0.95

In [73]:
ypred=lr.predict(xtest)
ypred

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2,
       0, 1, 1, 1, 1, 2])

In [74]:
ytest

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       0, 1, 1, 1, 1, 1])

In [75]:
accuracy_score(ytest,ypred)

0.96

In [76]:
confusion_matrix(ytest,ypred)

array([[15,  0,  0],
       [ 0, 20,  2],
       [ 0,  0, 13]], dtype=int64)

In [77]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.91      0.95        22
           2       0.87      1.00      0.93        13

    accuracy                           0.96        50
   macro avg       0.96      0.97      0.96        50
weighted avg       0.97      0.96      0.96        50



# GradientBoost

In [78]:
from sklearn.ensemble import GradientBoostingClassifier
learning_rates = [0.05,0.1,0.02,0.001,0.01,0.25]
for i in learning_rates:
    gra = GradientBoostingClassifier(learning_rate=i,n_estimators=100,random_state=100)
    gra.fit(xtrain,ytrain)
    print("Learning rate: ", i)
    print("Accuracy score (training): {0:.3f}".format(gra.score(xtrain, ytrain)))
    print("Accuracy score (validation): {0:.3f}".format(gra.score(xtest, ytest)))
    print()

Learning rate:  0.05
Accuracy score (training): 1.000
Accuracy score (validation): 0.980

Learning rate:  0.1
Accuracy score (training): 1.000
Accuracy score (validation): 0.980

Learning rate:  0.02
Accuracy score (training): 1.000
Accuracy score (validation): 0.980

Learning rate:  0.001
Accuracy score (training): 0.980
Accuracy score (validation): 0.960

Learning rate:  0.01
Accuracy score (training): 0.990
Accuracy score (validation): 0.980

Learning rate:  0.25
Accuracy score (training): 1.000
Accuracy score (validation): 0.980



In [79]:
ypred = gra.predict(xtest)
accuracy_score(ytest,ypred)


0.98

In [80]:
confusion_matrix(ytest,ypred)

array([[15,  0,  0],
       [ 0, 21,  1],
       [ 0,  0, 13]], dtype=int64)

In [81]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.95      0.98        22
           2       0.93      1.00      0.96        13

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



# Random Forest

In [82]:
from sklearn.ensemble import RandomForestClassifier
a = list(range(1,100,3))
scores = []
for i in a: 
    ran = RandomForestClassifier(max_depth=2,random_state=100,n_estimators=i)
    ran.fit(xtrain,ytrain)
    X_test_pred = ran.predict(xtest)
    results = accuracy_score(ytest,X_test_pred)
    scores.append(results)

In [83]:
scores

[0.76,
 0.98,
 0.96,
 0.96,
 0.94,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.94,
 0.94,
 0.94,
 0.94,
 0.94,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96]

In [84]:
max(scores)

0.98

# Decision Tree

In [85]:
from sklearn.tree import DecisionTreeClassifier

In [86]:
DC=DecisionTreeClassifier()

In [87]:
DC.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [88]:
DC.score(xtrain,ytrain)

1.0

In [89]:
ypred=DC.predict(xtest)
ypred

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 1, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2,
       0, 1, 1, 1, 1, 1])

In [90]:
ytest

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       0, 1, 1, 1, 1, 1])

In [91]:
accuracy_score(ytest,ypred)

0.96

In [92]:
confusion_matrix(ytest,ypred)

array([[15,  0,  0],
       [ 0, 21,  1],
       [ 0,  1, 12]], dtype=int64)

In [93]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.95      0.95      0.95        22
           2       0.92      0.92      0.92        13

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

